## Parameters
They are trainable variables, which can be changed, being part of the `nn.Module`

In [1]:
# Linear regression
import torch
from torch import nn

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()

        # Inicialize with random parameters to use gradient descent
        self.w1 = nn.Parameter(torch.randn(1,))
        self.w2 = nn.Parameter(torch.randn(1,))
        self.w3 = nn.Parameter(torch.randn(1,))
        self.w4 = nn.Parameter(torch.randn(1,))
        self.bias = nn.Parameter(torch.rand(1,))

        # Know parameters (original)
        self.biasp = 0.5
        self.w1p = 0.5
        self.w1p = 0.2
        self.w1p = 0.7
        self.w1p = 0.8

modelo = LinearRegressionModel()
print(f"As variáveis treinavei disponivéis são\n")
for name, parameter in modelo.named_parameters():
    print(f"Nome da variavel treinavel: {name}, {parameter}\n")

As variáveis treinavei disponivéis são

Nome da variavel treinavel: w1, Parameter containing:
tensor([-0.9015], requires_grad=True)

Nome da variavel treinavel: w2, Parameter containing:
tensor([0.5498], requires_grad=True)

Nome da variavel treinavel: w3, Parameter containing:
tensor([1.5878], requires_grad=True)

Nome da variavel treinavel: w4, Parameter containing:
tensor([0.4399], requires_grad=True)

Nome da variavel treinavel: bias, Parameter containing:
tensor([0.7997], requires_grad=True)

