In [1]:
import torch
from torch import nn # contains all of pytorchs building block.
import matplotlib.pyplot as plt

torch.__version__

'2.6.0+cpu'

## Data (preparing and loading)

Can be anything in ml

* Excels speadsheet
* Images and videos
* Audio 
* DNA


Ml it's a game in two parts
* Get the data into a numberical representation
* Build a model to learn the patterns

In [2]:
# Create some "know" data using LINEAR REGRESSION



# Create *know* parameters
weight = 0.7 # B
bias = 0.3 # A

# Create
X = torch.arange(0, 1, 0.02).unsqueeze(dim = 1)
y = weight * X + bias

print(X[:10]),print(y[:10])

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800]])
tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260]])


(None, None)

In [3]:
print(len(X), len(y))

50 50


## Spliting data into training and test sets

In [31]:
# Create a train/test split

train_split = int(0.8 * (len(X)))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]
print(len(X_train)), print(len(y_train)), print(len(X_test)), print(len(y_test))

40
40
10
10


(None, None, None, None)

### PyTorch model builds essentials
* torch.nn -> contains all of the buildings for computuional graphs
* torch.nn.Parameter -> what parameters should our model try and learn
* torch.nn.Module -> the base class for all neural netowrks
* torch.optim -> this where the optimizers in Pytorch live, helo with gradient descent
* def forward -> Defines what happens in the forward computation

### Making predictions using `torch.inference_mode()`

In [34]:
class LinearRegression(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()
        
        self.weight = nn.Parameter(torch.randn(1,))
        self.bias = nn.Parameter(torch.randn(1,))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.weight * x + self.bias

torch.manual_seed(42)
model_0 = LinearRegression()

with torch.inference_mode(): # or we can use the .no_grad()
    y_preds = model_0(X_test)
print(y_preds)
print(y_test)



tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])
tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])
