# Tensor randint

##### `Tensor.randint` it's a way to create tensors in any dimensions, `tensor.randint(x,y, (size))` gonna create the tensor with randoms numbers between x and y, like the exemple below:

In [25]:
import torch

scalar = torch.randint(1,10, ()) # OR TORCH.RANDINT(X, (SIZE)) CREATE A TENSOR WITH NUMBES LESS THEN X
vector = torch.randint(1,20,(2,)) # OR TORCH.RANDINT(X, (SIZE)) CREATE A TENSOR WITH NUMBES LESS THEN X
matrix = torch.randint(1,30,(3,3)) # OR TORCH.RANDINT(X, (SIZE)) CREATE A TENSOR WITH NUMBES LESS THEN X
tensor = torch.randint(1,40,(4,4)) # OR TORCH.RANDINT(X, (SIZE)) CREATE A TENSOR WITH NUMBES LESS THEN X
print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(5)
tensor([2, 4])
tensor([[24, 22, 11],
        [19, 15, 23],
        [ 2, 29, 22]])
tensor([[24,  1, 16,  7],
        [33,  1, 32, 34],
        [26, 34, 27, 26],
        [29, 25,  3, 18]])
