# Tensor arange

##### `Tensor.arange` it's a way to create tensors in any dimensions, `tensor.arange(start=x, end=y, step=z)` gonna create the tensor with end lenght, gonna start in start, and goes step by step

In [6]:
import torch

# IN THIS CASE SCALAR, MATRIX AND TENSORS CANT BE CREATE LIKE THIS `tensor.arange(start=x, end=y, step=z), HOW EVER I'TS USE ONETHER FUNCTIONS -> RESHAPE
# SCALAR CANT ;(
vector = torch.arange(0,5,1) 
matrix = torch.arange(0, 6).reshape(2, 3)
tensor = torch.arange(0, 24).reshape(2, 3,4)
print(vector)
print(matrix)
print(tensor)



tensor([0, 1, 2, 3, 4])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
