# Tensor ones

##### `Tensor.ones` it's a way to create tensors in any dimensions, `tensor.ones(size)` gonna create the tensor with 1 numbers with the size, like the exemple below:

In [1]:
import torch

scalar = torch.ones(()) 
vector = torch.ones((2)) 
matrix = torch.ones((3,3)) 
tensor = torch.ones((4,4)) 
print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(1.)
tensor([1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
