In [ ]:
# See the torchs version
import torch
print(torch.__version__)

2.4.1+cpu


# Introduction to the tensor

###    Creating using `torch.tensor`

In [9]:
# Scalar
scalar = torch.tensor(7)
print(scalar) # See the tensor
print(scalar.ndim) # See the tensor dimensions
print(scalar.item()) # Get the tensor as a int nubmer

tensor(7)
0
7


In [ ]:
# Vector

vector = torch.tensor([1,2,3])
print(vector) # See the tensor
print(vector.ndim) # See the dimensions
print(vector.shape) # See ROWs

tensor([1, 2, 3])
1
torch.Size([3])


In [17]:
# Matrix

matrix = torch.tensor([ [1,2,3], [4,5,6]])
print(matrix) # See the tensor
print(matrix.ndim) # See the tensor dimensions
print(matrix.shape) # See the ROWS/COLUMNS

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])


# Randons Tensors

`Create a random tensor -> Look at the data -> Update randoms numbers -> Look at the data`

In [19]:
random_tensors = torch.rand(3,3)
print(random_tensors) # See the tensors

tensor([[0.8242, 0.2673, 0.1189],
        [0.6538, 0.9852, 0.9926],
        [0.2319, 0.0351, 0.5422]])


# Zeros and ones tensors
`torch.zeros, torch.ones`

In [21]:
zeros_tensors = torch.zeros(3,3)
print(zeros_tensors)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [24]:
one_tensors = torch.ones(3,3)
print(one_tensors)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


# Creating a range of tensors

`torch.arange`

In [26]:
tensors_ranges = torch.arange(start=0, end=1, step=1)
print(tensors_ranges)

tensor([0])


In [27]:
tensors_ranges = torch.arange(start=0, end=100, step=10)
print(tensors_ranges)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [46]:
tensors_ranges = torch.arange(start=0, end=654, step=3, dtype=torch.int64)
print(tensors_ranges)

tensor([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
         84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123,
        126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
        168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207,
        210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249,
        252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291,
        294, 297, 300, 303, 306, 309, 312, 315, 318, 321, 324, 327, 330, 333,
        336, 339, 342, 345, 348, 351, 354, 357, 360, 363, 366, 369, 372, 375,
        378, 381, 384, 387, 390, 393, 396, 399, 402, 405, 408, 411, 414, 417,
        420, 423, 426, 429, 432, 435, 438, 441, 444, 447, 450, 453, 456, 459,
        462, 465, 468, 471, 474, 477, 480, 483, 486, 489, 492, 495, 498, 501,
        504, 507, 510, 513, 516, 519, 522, 525, 528, 531, 534, 5

# Create tensors like
`tensor.x_like`

In [ ]:
tensors_like = torch.zeros_like(tensors_ranges)
print(tensors_like) # This get the all numbers of tensors_ranges and transform into 0 with the like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])


In [31]:
tensors_like = torch.ones_like(tensors_ranges)
print(tensors_like) # This get the all numbers of tensors_ranges and transform into 0 with the like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])


In [34]:
tensors_like = torch.full_like(tensors_ranges, 10)
print(tensors_like) # This get the all numbers of tensors_ranges and transform into 0 with the like

tensor([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10])


In [48]:
tensors_like = torch.randn_like(tensors_ranges.to(torch.float))
print(tensors_like)

tensor([ 0.4526,  0.2082,  1.9648, -0.3859, -1.0269,  0.0661, -2.0183, -0.7160,
         0.4735,  0.1768,  0.1746, -0.6255,  0.8435, -0.1649,  0.5738,  0.0936,
         0.6149, -0.5784, -0.1579,  0.5867,  1.4121,  0.4130, -1.2806,  1.1760,
        -0.2030,  0.1163, -0.0651,  1.4445,  1.6362, -0.3415, -0.8976,  0.6354,
        -0.1896,  0.2641,  0.0113,  1.9465, -0.6006, -0.4956,  0.7732, -0.6521,
        -2.0713,  2.9314, -1.3166,  1.1424, -0.7618, -0.1697,  1.7925, -0.6306,
        -0.1826, -0.5659,  0.6743, -0.1997, -0.5701,  1.4454, -0.7417, -0.8904,
         0.4262,  0.2627, -1.0767, -0.6314,  0.0762, -0.3092, -0.5018,  0.5332,
         2.3700,  0.9924, -1.5296, -0.3334, -1.4482, -0.0031,  1.4099,  0.7905,
        -0.6044,  1.0017, -1.0471, -1.9743,  0.2443, -0.0411,  0.1144, -0.1283,
         0.6333, -0.3741,  0.5094, -0.9049,  1.2877,  0.8903, -0.6081, -0.0653,
        -0.2355,  0.8571, -0.9872, -0.7457,  1.0263, -0.0982, -1.4638,  0.8870,
         1.1409, -0.8934,  0.7158, -0.81

# Introduction to dtypes

#### Dtype it's the data type of the tensor (int8-64, float16-128 and etc..), this can be used to how the data gonna be representated in the memory

In [2]:
import torch

tensor_16 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16) 
tensor_32 = torch.tensor([1.0, 2.0, 3.0], dtype=None) #  By default it's float32 the dtype
tensor_64 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

print(tensor_16.dtype)
print(tensor_32.dtype)
print(tensor_64.dtype)

torch.float16
torch.float32
torch.float64


# Getting information from tensors (tensors attributes)

##### `tensor.dtype` to get information about the datatype of a tensor
##### `tensor.shape` to get information about shape of a tensor
##### `tensor.device` to get information about the device of a tensor

In [16]:
random_tensor = torch.rand(3,4)
print(random_tensor)
print(f"The datatype of the random tensor it's: {random_tensor.dtype}")
print(f"The shape of the random tensor it's: {random_tensor.shape}")
print(f"The device of the random tensor it's: {random_tensor.device}")

tensor([[0.9530, 0.4240, 0.2577, 0.1159],
        [0.6376, 0.5299, 0.6362, 0.9715],
        [0.5874, 0.7920, 0.8865, 0.8007]])
The datatype of the random tensor it's: torch.float32
The shape of the random tensor it's: torch.Size([3, 4])
The device of the random tensor it's: cpu


# Manipulation tensors
#### Add, sub, mul and divide

In [18]:
tensor = torch.tensor([1,2,3])

tensor_add = torch.add(tensor, 10)
tensor_sub = torch.sub(tensor, 10)
tensor_mul = torch.mul(tensor, 10)
tensor_div = torch.div(tensor, 10)

print(f"The process of add numbers in tensor it's 'torch.operation(tensor, x), operations it's the operation that we use (add, sub, mul and div) x it's the number that gonna be add,")
print(tensor)
print(F"Add 10 ->: {torch.add(tensor, 10)}")
print(F"Sub 10 ->: {torch.sub(tensor, 10)}")
print(F"Mul 10 ->: {torch.mul(tensor, 10)}")
print(F"Div 10 ->: {torch.div(tensor, 10)}")

The process of add numbers in tensor it's 'torch.operation(tensor, x), operations it's the operation that we use (add, sub, mul and div) x it's the number that gonna be add,
tensor([1, 2, 3])
Add 10 ->: tensor([11, 12, 13])
Sub 10 ->: tensor([-9, -8, -7])
Mul 10 ->: tensor([10, 20, 30])
Div 10 ->: tensor([0.1000, 0.2000, 0.3000])


# Reshaping and stacking

### Reshape it's the process of change the dimensions of a tensor without change the data, we can manipulate like we want.
##### Here we have a vector with 9 itens, it's ( , 9) dimension doens't have rows, just a sequency

In [12]:
import torch

tensor = torch.arange(1, 10, dtype=torch.float32)
print(tensor, tensor.size())

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


##### Now we have a matrix, with row and columns (1 , 9)

In [10]:
tensor_reshaped = tensor.reshape(1, 9)
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


##### Now we have a matrix, with rows and column (9, 1)

In [11]:
tensor_reshaped = tensor.reshape(9, 1)
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


##### Another example, now we have a matrix (3, 4) and we gonna reshape that

In [16]:
tensor = torch.arange(1, 13, dtype=torch.float32).reshape(3, 4)
print(tensor, tensor.size())

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) torch.Size([3, 4])


##### Now we gonna transform this matrix in a (6, 2)

In [18]:
tensor_reshaped = tensor.reshape(6, 2)
print(tensor_reshaped, tensor_reshaped.size())

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]) torch.Size([6, 2])


# Stacking

#### Stacking it's the process of join two or more tensors in one

##### Here we wave a vector (1, 5) and we want to create a (3, 5) matrix with the values of the vector

In [19]:
tensor = torch.arange(1, 6, dtype=torch.float16)
print(tensor, tensor.shape)

tensor([1., 2., 3., 4., 5.], dtype=torch.float16) torch.Size([5])


In [22]:
tensors_stacked = torch.stack([tensor, tensor, tensor], dim=0)
print(tensors_stacked, tensors_stacked.shape)

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]], dtype=torch.float16) torch.Size([3, 5])


##### And we can change for a (5, 3), just changing the DIM, so DIM = 1 represents join the tensors in horizontal, and DIM = 0 in vertical

In [23]:
tensors_stacked = torch.stack([tensor, tensor, tensor], dim=1)
print(tensors_stacked, tensors_stacked.shape)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.]], dtype=torch.float16) torch.Size([5, 3])


# Squeeze
##### It's the process of REMOVE all SINGLE ONE DIMENSIONS, we use the `tensor.squeeze(dim)`, the dim it's the dimension that you want to remove if it's single one `tensor.squeeze(dim = 0)`, if be SINGLE ONEa, will remove only that, like the example bellow:

In [5]:
import torch
tensor = torch.randint(1, 10, (3, 2, 1), dtype=torch.float16)
print(f"Before the squeeze, the tensor it's:\n{tensor}")
print(f"Before the squeeze, the tensor shape it's: {tensor.shape}\n\n")

tensor_squeezed = tensor.squeeze()
print(f"After the squeeze, the tensor it's:\n{tensor_squeezed}")
print(f"After the squeeze, the tensor shape it's: {tensor_squeezed.shape}")

Before the squeeze, the tensor it's:
tensor([[[3.],
         [2.]],

        [[5.],
         [1.]],

        [[3.],
         [6.]]], dtype=torch.float16)
Before the squeeze, the tensor shape it's: torch.Size([3, 2, 1])


After the squeeze, the tensor it's:
tensor([[3., 2.],
        [5., 1.],
        [3., 6.]], dtype=torch.float16)
After the squeeze, the tensor shape it's: torch.Size([3, 2])


In [9]:
tensor = torch.rand((1, 2, 2, 1), dtype=torch.float16)
print(f"Before the squeeze, the tensor it's:\n{tensor}")
print(f"Before the squeeze, the tensor shape it's: {tensor.shape}\n\n")

tensor_squeezed = tensor.squeeze(dim = 0)
print(f"After the squeeze, the tensor it's:\n{tensor_squeezed}")
print(f"After the squeeze, the tensor shape it's: {tensor_squeezed.shape}")

# HERE JUST SQUEEZE THE DIM 0 IF HAVE A SINGLE ONE DIMENSION

Before the squeeze, the tensor it's:
tensor([[[[0.6675],
          [0.4497]],

         [[0.5869],
          [0.2930]]]], dtype=torch.float16)
Before the squeeze, the tensor shape it's: torch.Size([1, 2, 2, 1])


After the squeeze, the tensor it's:
tensor([[[0.6675],
         [0.4497]],

        [[0.5869],
         [0.2930]]], dtype=torch.float16)
After the squeeze, the tensor shape it's: torch.Size([2, 2, 1])


# Unsqueeze
##### It's the process of ADD a SINGLE ONE DIMENSION in EXIST TENSOR, we use the `tensor.unsqueeze(dim)`, the dim it's the dimension that where gonna be placed the new dimension

In [24]:
tensor = torch.rand((2, 1), dtype=torch.float16)
print(f"Before the unsqueeze, the tensor it's:\n{tensor}")
print(f"Before the unsqueeze, the tensor shape it's: {tensor.shape}\n\n")

tensor_unsqueezed = tensor.unsqueeze(dim = 0)
print(f"After the unsqueeze, the tensor it's:\n{tensor_unsqueezed}")
print(f"After the unsqueeze, the tensor shape it's: {tensor_unsqueezed.shape}")



Before the unsqueeze, the tensor it's:
tensor([[0.7075],
        [0.0435]], dtype=torch.float16)
Before the unsqueeze, the tensor shape it's: torch.Size([2, 1])


After the unsqueeze, the tensor it's:
tensor([[[0.7075],
         [0.0435]]], dtype=torch.float16)
After the unsqueeze, the tensor shape it's: torch.Size([1, 2, 1])


# Permuting 
##### It's the process of REORDER the DIMENSIONS of a TENSOR, we use `tensor.permute(new order of the dimensions)`

In [28]:
tensor = torch.rand((1, 2, 3), dtype=torch.float16)
print(f"Before the permute, the tensor it's:\n{tensor}")
print(f"Before the permute, the tensor shape it's: {tensor.shape}\n\n")

tensor_permuted = tensor.permute(2, 0, 1)
print(f"After the permute, the tensor it's:\n{tensor_permuted}")
print(f"After the permute, the tensor shape it's: {tensor_permuted.shape}")


Before the permute, the tensor it's:
tensor([[[0.0625, 0.1938, 0.7822],
         [0.3535, 0.3794, 0.8101]]], dtype=torch.float16)
Before the permute, the tensor shape it's: torch.Size([1, 2, 3])


After the permute, the tensor it's:
tensor([[[0.0625, 0.3535]],

        [[0.1938, 0.3794]],

        [[0.7822, 0.8101]]], dtype=torch.float16)
After the permute, the tensor shape it's: torch.Size([3, 1, 2])


# Indexing 
##### It's the process of acess the data for index, we use `tensor[x, y, z...]` the letters identify the position of where you want to acess, start's in 0 until the last number - 1

In [5]:
import torch
tensor = torch.tensor([0, 1, 2, 3, 4], dtype=torch.float16)
print(tensor)
print(f"To acess the first element we use the 0, like the example -> tensor[0] = {tensor[0]}")

tensor([0., 1., 2., 3., 4.], dtype=torch.float16)
To acess the first element we use the 0, like the example -> tensor[0] = 0.0


In [6]:
# ACESS THE SECOND, THIRD AND MORE....
print(f"To acess the second element we use the 1, like the example -> tensor[1] = {tensor[1]}")
print(f"To acess the third element we use the 2, like the example -> tensor[2] = {tensor[2]}")

To acess the second element we use the 1, like the example -> tensor[1] = 1.0
To acess the third element we use the 2, like the example -> tensor[2] = 2.0
