# Matrix mulplication -> (By ROWS and COLUMNS, we called DOT MULTIPLICATION)
### In this way we multiply the rows for the first matrix by the columnds for the second

#### An example of that it's 
#### tensor1 (3, 2)
#### tensor2 (2, 3)
####  ..............   6  = 6
#### We multiply the terms in vertical, if the terms after the multiplication are equal and the rows of first tensor and columns of second are equal we can DOT this

In [5]:
import torch

tensor_one = torch.randint(0, 10, (3, 2), dtype = torch.float32)
tensor_two = torch.randint(0, 10, (2, 3), dtype = torch.float32)

print(f"The first tensor created are:\n{tensor_one}")
print(f"The second tensor created are:\n{tensor_two}")

mult_tensors = torch.matmul(tensor_one, tensor_two)
print(f"The multiplied tensor are:\n{mult_tensors}")

The first tensor created are:
tensor([[8., 8.],
        [7., 0.],
        [4., 5.]])
The second tensor created are:
tensor([[2., 6., 6.],
        [5., 7., 9.]])
The multiplied tensor are:
tensor([[ 56., 104., 120.],
        [ 14.,  42.,  42.],
        [ 33.,  59.,  69.]])


#### So will multiply the first row in the first tensor (8, 8) by the first column in the second tensor (2, 5), So 8*2 + 8*5 -> 16 + 40 = 56
#### And will do this in all the rows and columnds, because of this we need to have the same quantity of the rows 1t and the columns 2t, so this will created a tensor by -> (number_of_rows_1_tensor, number_of_columns_2_tensor), in this case of example we are, (3, 2) first tensor and (2, 3) second tensor gonna be created a (3, 3) tensor