# Matrix multiplication -> (Element by element)

#### There are two ways to multiplacation matrix, one of it's per elememnt using the normal symbols of math in progamming, the `*`

In [12]:
import torch

tensor_one = torch.randint(0, 10, (2, 2), dtype = torch.float32)
print(f"The first tensor created are:\n{tensor_one}")
print(f"Atrributes about, tensor dimensions:{tensor_one.dtype}, device:{tensor_one.device}")

The first tensor created are:
tensor([[4., 7.],
        [6., 4.]])
Atrributes about, tensor dimensions:torch.float32, device:cpu


In [15]:
tensor_two = torch.randint(0, 10, (2, 2), dtype = torch.float32)
print(f"The second tensor created are:\n{tensor_two}")
print(f"Atrributes about, tensor dimensions:{tensor_two.dtype}, device:{tensor_two.device}, shape: {tensor_two.shape}")

The second tensor created are:
tensor([[8., 4.],
        [6., 3.]])
Atrributes about, tensor dimensions:torch.float32, device:cpu, shape: torch.Size([2, 2])


In [17]:
# Multiplication element by element
mult_tensors = tensor_one * tensor_two
print(f"The multiplication of element by element in tensors result in a new tensor:\n{mult_tensors}")

The multiplication of element by element in tensors result in a new tensor:
tensor([[32., 28.],
        [36., 12.]])


### We can see, in this way the first elemnt in first tensor gonna be multiply for the first elemnt in second tensor, like the example, e = element, t = tensor:


#### A matrix 2x2:

` [1e1t * 1e2t     |      2e1t * 2e2t]`

` [3e1t * 3e2t     |     4e1t * 4e2t]`   