# EASY LEVEL
##### Create two 2x2 tensors and perform addition, subtraction and multiplication operations element by element.

In [8]:
import torch

tensor1 = torch.randn((2, 2), dtype = torch.float16)
tensor2 = torch.randn((2, 2), dtype = torch.float16)

print(f"Tensor1\n{tensor1}")
print(f"Tensor2\n{tensor2}")

print(f"\n\n\nTensor1 + Tensor2 =\n{tensor1 + tensor2}")
print(f"\nTensor1 - Tensor2 =\n{tensor1 - tensor2}")
print(f"\nTensor1 * Tensor2 =\n{tensor1 * tensor2}")
print(f"\nTensor1 / Tensor2 =\n{tensor1 / tensor2}")


Tensor1
tensor([[ 0.6924, -0.0331],
        [-0.5967, -0.2023]], dtype=torch.float16)
Tensor2
tensor([[-1.0078, -0.1583],
        [-0.3652, -0.3853]], dtype=torch.float16)



Tensor1 + Tensor2 =
tensor([[-0.3154, -0.1914],
        [-0.9619, -0.5874]], dtype=torch.float16)

Tensor1 - Tensor2 =
tensor([[ 1.7002,  0.1252],
        [-0.2314,  0.1830]], dtype=torch.float16)

Tensor1 * Tensor2 =
tensor([[-0.6978,  0.0052],
        [ 0.2179,  0.0779]], dtype=torch.float16)

Tensor1 / Tensor2 =
tensor([[-0.6870,  0.2094],
        [ 1.6338,  0.5249]], dtype=torch.float16)
