# Tenosr full

##### `Tensor.full` it's a way to create tensors in any dimensions, `tensor.full((size), x)` x it's the number that go complete the tensor, like the exemple below:

In [1]:
import torch

scalar = torch.full((), 1)
vector = torch.full((2,), 2)
matriz = torch.full((3,3), 3)
tensor = torch.full((4,4,4), 4)
print(scalar)
print(vector)
print(matriz)
print(tensor)

tensor(1)
tensor([2, 2])
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])
tensor([[[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]]])
