# Tenosr rand

##### `Tensor.rand` it's a way to create tensors in any dimensions, `tensor.rand(size)` gonna create the tensor with randoms numbers between 0 and 1, like the exemple below:

In [2]:
import torch

scalar = torch.rand(1)
vector = torch.rand(2,)
matrix = torch.rand(3,3)
tensor = torch.rand(4,4,4)
print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor([0.8967])
tensor([0.5230, 0.5589])
tensor([[0.8490, 0.3777, 0.8176],
        [0.5912, 0.1432, 0.9682],
        [0.6009, 0.9967, 0.7352]])
tensor([[[0.2637, 0.4994, 0.2404, 0.3204],
         [0.1498, 0.0986, 0.6358, 0.5076],
         [0.3560, 0.4561, 0.1183, 0.7246],
         [0.7893, 0.9286, 0.9081, 0.3790]],

        [[0.3095, 0.5679, 0.6093, 0.1012],
         [0.6973, 0.1020, 0.6470, 0.5815],
         [0.5706, 0.4873, 0.8129, 0.2800],
         [0.9877, 0.1047, 0.8835, 0.2955]],

        [[0.8261, 0.7956, 0.1925, 0.3494],
         [0.5993, 0.9791, 0.3860, 0.4968],
         [0.5612, 0.9265, 0.0461, 0.9692],
         [0.4124, 0.8956, 0.4204, 0.5672]],

        [[0.2058, 0.3900, 0.8451, 0.8807],
         [0.0367, 0.7638, 0.2982, 0.2303],
         [0.4153, 0.7862, 0.3331, 0.9092],
         [0.6770, 0.1765, 0.3368, 0.0541]]])
