# Tensor zeros

##### `Tensor.zeros` it's a way to create tensors in any dimensions, `tensor.zeros(size)` gonna create the tensor 0 numbers with the size, like the exemple below:

In [5]:
import torch

scalar = torch.zeros(()) 
vector = torch.zeros((2)) 
matrix = torch.zeros((3,3)) 
tensor = torch.zeros((4,4)) 
print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(0.)
tensor([0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
