# Tensor like

##### `Tensor.x_like` it's a way to create/convert/copy tensors in any dimensions, `tensor.x_like(tensor)` gonna create the tensor with the especify X with the size, this function copy e exist tensor1 and create a new with the same dimensions and shape like the tensor1, just change the numbers,  like the exemple below:


In [5]:
import torch

# Create tensors with 0 and 1
scalar = torch.rand(1)
vector = torch.rand(2,)
matrix = torch.rand(3,3)
tensor = torch.rand(4,4,4)
print("Orignals tensors")
print(scalar)
print(vector)
print(matrix)
print(tensor)
print("\n\n\n")

# Convert/Create to zeros

print("Converrt the TENSORS RAND TO TENSORS ZEROS")
scalar = torch.zeros_like(scalar) 
vector = torch.zeros_like(vector) 
matrix = torch.zeros_like(matrix) 
tensor = torch.zeros_like(tensor) 
print(scalar)
print(vector)
print(matrix)
print(tensor)
print("\n\n\n")



# Convert/Create to ones
print("Converrt the TENSORS ZEROS TO TENSORS ONES")
scalar = torch.ones_like(scalar) 
vector = torch.ones_like(vector) 
matrix = torch.ones_like(matrix) 
tensor = torch.ones_like(tensor) 
print(scalar)
print(vector)
print(matrix)
print(tensor)
print("\n\n\n")

# Convert/Create to randint
print("Converrt the TENSORS ONES TO TENSORS RANDINT")
scalar = torch.randint_like(scalar, 1, 10) 
vector = torch.randint_like(vector, 1, 10) 
matrix = torch.randint_like(matrix, 1, 10) 
tensor = torch.randint_like(tensor, 1, 10) 
print(scalar)
print(vector)
print(matrix)
print(tensor)

Orignals tensors
tensor([0.0909])
tensor([0.0385, 0.9308])
tensor([[0.0175, 0.6589, 0.7822],
        [0.6257, 0.4552, 0.2277],
        [0.5991, 0.3148, 0.3560]])
tensor([[[0.4509, 0.8665, 0.7031, 0.6603],
         [0.8245, 0.9429, 0.9059, 0.9914],
         [0.0471, 0.2364, 0.2474, 0.3516],
         [0.3192, 0.8384, 0.9492, 0.1950]],

        [[0.4891, 0.6566, 0.0261, 0.4475],
         [0.4722, 0.1805, 0.7151, 0.6277],
         [0.4931, 0.4175, 0.1453, 0.0694],
         [0.0838, 0.1822, 0.2372, 0.4205]],

        [[0.3204, 0.2235, 0.4901, 0.4984],
         [0.1481, 0.4999, 0.2398, 0.9868],
         [0.5600, 0.3854, 0.3025, 0.6708],
         [0.7055, 0.5309, 0.1648, 0.6740]],

        [[0.6510, 0.4320, 0.7746, 0.1439],
         [0.7569, 0.2076, 0.9163, 0.2173],
         [0.3276, 0.2180, 0.1938, 0.2990],
         [0.0466, 0.8120, 0.7378, 0.2280]]])




Converrt the TENSORS RAND TO TENSORS ZEROS
tensor([0.])
tensor([0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]